# Generated by Django 3.1 on 2020-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Adopted', 'adopted'), ('Available', 'available'), ('Mismatched', 'mismatched')], default='Available', max_length=50)),
                ('pet_type', models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('Birds', 'birds')], default='Dog', max_length=50)),
                ('pet_name', models.CharField(default='No Name', max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
